name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-scan:
    runs-on: ubuntu-latest   # using Linux runner for simplicity

    env:
      REPORTS_DIR: reports
      IMAGE_NAME: my-python-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create reports directories
        run: |
          mkdir -p $REPORTS_DIR/unittest_reports
          mkdir -p $REPORTS_DIR/flake8_reports
          mkdir -p $REPORTS_DIR/banditreports

      - name: Run Unit Tests with JSON Report
        shell: bash
        run: |
          timestamp=$(date +"%Y%m%d_%H%M%S")
          export PYTHONPATH=$PYTHONPATH:$PWD
          pytest fastapi_todo_app/tests flask_hello_app/tests flask_users_app/tests \
              --json-report \
              --json-report-file=$REPORTS_DIR/unittest_reports/unit_test_report_$timestamp.json

      - name: Run Flake8 Linting
        shell: bash
        run: |
          flake8 flask_hello_app fastapi_todo_app flask_users_app \
              --format=html \
              --htmldir=$REPORTS_DIR/flake8_reports

      - name: Run Bandit Security Scan
        shell: bash
        run: |
          timestamp=$(date +"%Y%m%d_%H%M%S")
          bandit -r flask_hello_app fastapi_todo_app flask_users_app \
              -f json \
              -o $REPORTS_DIR/banditreports/bandit_report_$timestamp.json
