name: Python Lint & Security

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_security:
    name: Lint & Security Checks
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python 3.14
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install project dependencies from requirements.txt
          pip install -r requirements.txt
          # Install linting and security tools
          pip install flake8 flake8-html bandit

      # 4️⃣ Create report directories
      - name: Prepare report directories
        run: |
          mkdir -p reports/flake8_reports
          mkdir -p reports/banditreports

      # 5️⃣ Run Flake8 lint and generate HTML report
      - name: Run Flake8 Lint
        run: |
          TIMESTAMP=$(date +'%Y%m%d_%H%M%S')
          flake8 flask_hello_app fastapi_todo_app flask_users_app \
            --format=html --htmldir=reports/flake8_reports_$TIMESTAMP
        shell: bash

      # 6️⃣ Run Bandit security scan and save JSON report
      - name: Run Bandit Security Scan
        run: |
          TIMESTAMP=$(date +'%Y%m%d_%H%M%S')
          bandit -r flask_hello_app fastapi_todo_app flask_users_app \
            -f json -o reports/banditreports/bandit_report_$TIMESTAMP.json
        shell: bash
