name: Python CI + Docker Push

on:
  push:
    branches:
      - main

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    env:
      REPORTS_DIR: reports
      IMAGE_NAME: my-python-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create report directories
        run: |
          mkdir -p $REPORTS_DIR/unittest_reports
          mkdir -p $REPORTS_DIR/banditreports
          mkdir -p $REPORTS_DIR/flake8_reports

      - name: Run tests + lint + bandit
        run: |
          timestamp=$(date +"%Y%m%d_%H%M%S")
          pytest fastapi_todo_app/tests flask_hello_app/tests flask_users_app/tests \
              --json-report \
              --json-report-file=$REPORTS_DIR/unittest_reports/unit_test_report_$timestamp.json
          flake8 flask_hello_app fastapi_todo_app flask_users_app --format=html --htmldir=$REPORTS_DIR/flake8_reports
          bandit -r flask_hello_app fastapi_todo_app flask_users_app -f json -o $REPORTS_DIR/banditreports/bandit_report_$timestamp.json

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest
