name: Python CI - Lint & Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13  # Compatible with your packages

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create report directories
        run: |
          mkdir -p reports/flake8_reports
          mkdir -p reports/banditreports

      - name: Run Flake8 linting
        run: |
          flake8 flask_hello_app fastapi_todo_app flask_users_app \
            --format=html --htmldir=reports/flake8_reports

      - name: Run Bandit security scan
        run: |
          timestamp=$(date +'%Y%m%d_%H%M%S')
          bandit -r flask_hello_app fastapi_todo_app flask_users_app \
            -f json -o reports/banditreports/bandit_report_$timestamp.json

      - name: Show success message
        run: |
          echo "Linting and Bandit scans completed!"
          echo "Flake8 HTML report: reports/flake8_reports"
          echo "Bandit JSON report: reports/banditreports/bandit_report_$timestamp.json"
