name: Security Reports

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bandit_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit
        run: |
          mkdir -p reports/banditreports
          timestamp=$(date +'%Y%m%d_%H%M%S')
          bandit -r . -f json -o reports/banditreports/bandit_report_$timestamp.json
        continue-on-error: true   # <<<<<< This prevents workflow failure
