name: Trivy Filesystem Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit trivy-python

      - name: Create reports folder
        run: |
          mkdir -p reports/trivy_reports

      - name: Run Trivy filesystem scan
        run: |
          TIMESTAMP=$(date +'%Y%m%d_%H%M%S')
          trivy fs . --scanners vuln --format json --output reports/trivy_reports/trivy_fs_report_$TIMESTAMP.json

      - name: Commit and push reports
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add reports/trivy_reports/*
          git commit -m "Add Trivy FS report $TIMESTAMP" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
