name: Security and Unit Test Reports

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security_and_tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit pytest pytest-json-report fastapi[all] flask requests

      # ---------------- Bandit Scan ----------------
      - name: Run Bandit Security Scan
        run: |
          mkdir -p reports\banditreports
          $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
          bandit -r . -f json -o reports\banditreports\bandit_report_$timestamp.json
        continue-on-error: true

      # ---------------- Unit Tests ----------------
      - name: Run Unit Tests for FastAPI app
        run: |
          mkdir -p reports\unittest_reports
          $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
          $env:PYTHONPATH = "$PWD\fastapi_todo_app"
          pytest fastapi_todo_app/tests --json-report --json-report-file=reports/unittest_reports/unit_test_report_fastapi_$timestamp.json
        continue-on-error: true

      - name: Run Unit Tests for Flask Hello App
        run: |
          mkdir -p reports\unittest_reports
          $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
          $env:PYTHONPATH = "$PWD\flask_hello_app"
          pytest flask_hello_app/tests --json-report --json-report-file=reports/unittest_reports/unit_test_report_flask_hello_$timestamp.json
        continue-on-error: true

      - name: Run Unit Tests for Flask Users App
        run: |
          mkdir -p reports\unittest_reports
          $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
          $env:PYTHONPATH = "$PWD\flask_users_app"
          pytest flask_users_app/tests --json-report --json-report-file=reports/unittest_reports/unit_test_report_flask_users_$timestamp.json
        continue-on-error: true
