name: CI Reports

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-scan:
    runs-on: windows-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3️⃣ Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4️⃣ Run unit tests and save JSON report
    - name: Run Unit Tests
      run: |
        $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        pytest --json-report --json-report-file="reports/unittest_reports/unit_test_report_$timestamp.json"

    # 5️⃣ Build Docker image
    - name: Build Docker image
      run: |
        docker build -t my-python-app:latest -f docker/Dockerfile .

    # 6️⃣ Scan Docker image with Trivy and save JSON report
    - name: Trivy Image Scan
      run: |
        $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        trivy image my-python-app:latest --scanners vuln,license --format json --output "reports/trivy_reports/trivy_image_report_$timestamp.json"
