name: Python Backend Lint & Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-security:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Set up Python 3.14
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.14

    # 3️⃣ Upgrade pip
    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    # 4️⃣ Install dependencies from requirements.txt
    - name: Install dependencies
      run: pip install -r requirements.txt

    # 5️⃣ Install Flake8 HTML plugin for HTML reports
    - name: Install Flake8 HTML
      run: pip install flake8-html

    # 6️⃣ Run Flake8 linting on all apps and save HTML report
    - name: Run Flake8 linting
      run: |
        mkdir -p reports/flake8_reports
        flake8 flask_hello_app fastapi_todo_app flask_users_app --format=html --htmldir=reports/flake8_reports

    # 7️⃣ Run Bandit scan and save JSON report with timestamp
    - name: Run Bandit security scan
      run: |
        mkdir -p reports/banditreports
        TIMESTAMP=$(date +'%Y%m%d_%H%M%S')
        bandit -r flask_hello_app fastapi_todo_app flask_users_app -f json -o reports/banditreports/bandit_report_$TIMESTAMP.json

    # 8️⃣ Show completion message
    - name: Show summary
      run: |
        echo "Linting and Bandit scans completed."
        echo "Flake8 HTML report: reports/flake8_reports"
        echo "Bandit JSON report: reports/banditreports/bandit_report_$(date +'%Y%m%d_%H%M%S').json"
